version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: coming_soon
  timestamp: 1560370512
layout:
  top: {  }
  /navigation/:
    -
      - 'logo-9841 20'
      - 'menu-7574 60'
      - 'social-2794 20'
    -
      - simplecontent-8300
  /slideshow/: {  }
  /header/: {  }
  /above/: {  }
  /showcase/: {  }
  /utility/: {  }
  /feature/: {  }
  /container-main/:
    -
      -
        'sidebar 20': {  }
      -
        'mainbar 60':
          -
            - simplecounter-4200
      -
        'aside 20': {  }
  /expanded/: {  }
  /extension/: {  }
  /bottom/:
    -
      - blockcontent-6645
  footer: {  }
  /copyright/: {  }
  offcanvas: {  }
structure:
  top:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  navigation:
    type: section
    attributes:
      boxed: ''
  slideshow:
    type: section
    attributes:
      boxed: ''
  header:
    attributes:
      boxed: ''
      class: ''
  above:
    type: section
    attributes:
      boxed: ''
      class: ''
  showcase:
    type: section
    attributes:
      boxed: ''
      class: ''
  utility:
    type: section
    attributes:
      boxed: ''
      class: ''
  feature:
    type: section
    attributes:
      boxed: ''
      class: ''
  sidebar:
    type: section
    subtype: aside
    attributes:
      class: ''
  mainbar:
    type: section
    subtype: main
    title: Main
    attributes:
      class: ''
      variations: ''
  aside:
    attributes:
      class: ''
  container-main:
    attributes:
      boxed: ''
      class: ''
      extra: {  }
  expanded:
    type: section
    attributes:
      boxed: ''
      class: ''
  extension:
    type: section
    attributes:
      boxed: ''
      class: ''
  bottom:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - children
  copyright:
    type: section
    attributes:
      boxed: ''
      class: center
      variations: ''
    inherit:
      outline: default
      include:
        - children
  offcanvas:
    inherit:
      outline: default
      include:
        - attributes
        - children
content:
  logo-9841:
    title: 'Logo / Image'
    inherit:
      outline: default
      include:
        - attributes
        - block
      particle: logo-2704
  menu-7574:
    inherit:
      outline: default
      include:
        - attributes
        - block
      particle: menu-2872
  social-2794:
    inherit:
      outline: default
      include:
        - attributes
        - block
      particle: social-3096
  simplecontent-8300:
    title: 'Coming Soon'
    attributes:
      class: ''
      title: ''
      items:
        -
          layout: header
          created_date: ''
          content_title: 'Coming Soon'
          author: ''
          leading_content: 'Website under construction.'
          main_content: ''
          readmore_label: ''
          readmore_link: ''
          readmore_class: ''
          readmore_target: _self
          title: 'Coming Soon'
  simplecounter-4200:
    title: 'Simple Counter'
    attributes:
      title: 'Stay Tuned'
      desc: 'We are working on a new and exciting template that we think you will really like.'
      date: '31'
      year: '2020'
      daytext: Day
      daystext: Days
      hourtext: Hour
      hourstext: Hours
      minutetext: Minute
      minutestext: Minutes
      secondtext: Second
      secondstext: Seconds
    block:
      variations: center
  blockcontent-6645:
    title: 'Block Content'
    attributes:
      class: ''
      title: ''
      icon: ''
      image: ''
      headline: 'Have Something to Tell Us?'
      description: 'Ideas, Suggestions or Review'
      linktext: 'Contact Us'
      link: '#'
      linkclass: button-2
      linktarget: _self
      subcontents: {  }
    block:
      class: nomarginbottom
      variations: center
