ordering:
  home: ''
  features:
    overview: ''
    particles: ''
    typography: ''
    block-variations: ''
    documentation: ''
    forum-support: ''
    download: ''
  pages:
    -
      about-us: ''
      pricing: ''
      portfolio: ''
      blog: ''
    -
      contact: ''
      error: ''
      coming-soon: ''
      offline: ''
  sample-layouts:
    fullwidth: ''
    left-sidebar: ''
    right-sidebar: ''
    two-sidebars: ''
    two-sidebars-left: ''
    two-sidebars-right: ''
    rows-columns: ''
  styles:
    __particle-FRMPX: ''
items:
  home:
    id: 101
  features:
    id: 104
  features/overview:
    id: 105
  features/particles:
    id: 168
  features/typography:
    id: 106
  features/block-variations:
    id: 107
  features/documentation:
    id: 108
  features/forum-support:
    id: 109
  features/download:
    id: 124
  pages:
    id: 110
    dropdown_dir: right
    dropdown_hide: '0'
    width: 400px
  pages/about-us:
    id: 111
  pages/pricing:
    id: 114
  pages/portfolio:
    id: 115
  pages/blog:
    id: 118
  pages/contact:
    id: 119
  pages/error:
    id: 120
  pages/coming-soon:
    id: 121
  pages/offline:
    id: 122
  sample-layouts:
    id: 180
  sample-layouts/fullwidth:
    id: 181
  sample-layouts/left-sidebar:
    id: 182
  sample-layouts/right-sidebar:
    id: 183
  sample-layouts/two-sidebars:
    id: 184
  sample-layouts/two-sidebars-left:
    id: 186
  sample-layouts/two-sidebars-right:
    id: 187
  sample-layouts/rows-columns:
    id: 185
  styles:
    id: 123
    dropdown: fullwidth
    dropdown_dir: center
    dropdown_hide: '1'
    width: 30rem
  styles/__particle-FRMPX:
    type: particle
    particle: custom
    title: 'Custom HTML'
    options:
      particle:
        enabled: '1'
        html: "<div class=\"g-grid g-preset-thumbnails center\">\n    <div class=\"g-block\">\n        <div class=\"g-content\">\n            <a href=\"?presets=preset1\">\n                <img src=\"gantry-media://rocketlauncher/styles/preset1.jpg\" alt=\"Preset 1\">\n                <br>\n                <span>Preset 1</span>\n            </a>\n        </div>\n    </div>\n    <div class=\"g-block\">\n        <div class=\"g-content\">\n            <a href=\"?presets=preset2\">\n                <img src=\"gantry-media://rocketlauncher/styles/preset2.jpg\" alt=\"Preset 2\">\n                <br>\n                <span>Preset 2</span>\n            </a>\n        </div>\n    </div>\n    <div class=\"g-block\">\n        <div class=\"g-content\">\n            <a href=\"?presets=preset3\">\n                <img src=\"gantry-media://rocketlauncher/styles/preset3.jpg\" alt=\"Preset 3\">\n                <br>\n                <span>Preset 3</span>\n            </a>\n        </div>\n    </div>\n    <div class=\"g-block\">\n        <div class=\"g-content\">\n            <a href=\"?presets=preset4\">\n                <img src=\"gantry-media://rocketlauncher/styles/preset4.jpg\" alt=\"Preset 4\">\n                <br>\n                <span>Preset 4</span>\n            </a>\n        </div>\n    </div>\n</div>"
        twig: '0'
        filter: '0'
      block:
        extra: {  }
    enabled: '1'
