preset: preset2
base:
  text-active-color: '#f12844'
accent:
  color-1: '#f12844'
button:
  background-color: '#f12844'
menustyle:
  background-active: '#f12844'
navigation:
  background: '#000000'
  background-image: ''
  text-color: '#ffffff'
offcanvas:
  background: '#f12844'
