name: 294
timestamp: 1562114186
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: rows_and_columns
  timestamp: 1560370512
positions:
  header-a: 'Header A'
  above-a: 'Above A'
  feature-a: 'Feature A'
  showcase-a: 'Showcase A'
  sidebar-a: 'Sidebar A'
  mainbar-a: 'MainBar A'
  aside-a: 'Aside A'
  expanded-a: 'Expanded A'
  extension-a: 'Extension A'
  bottom-a: 'Bottom A'
sections:
  top: Top
  navigation: Navigation
  slideshow: Slideshow
  above: Above
  feature: Feature
  showcase: Showcase
  utility: Utility
  expanded: Expanded
  extension: Extension
  bottom: Bottom
  copyright: Copyright
  header: Header
  sidebar: Sidebar
  aside: Aside
  mainbar: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-9841: 'Logo / Image'
    logo-9485: 'Logo / Image'
  menu:
    menu-7574: Menu
  social:
    social-2794: Social
    social-3786: Social
  simplecontent:
    simplecontent-7052: 'Rows & Columns Example'
  custom:
    custom-2875: 'Equal Width Examples'
    custom-4860: 'Single Block per Row'
    custom-9868: 'Two Blocks per Row'
    custom-4807: 'Two Blocks per Row'
    custom-3780: 'Three Blocks per Row'
    custom-7528: 'Three Blocks per Row'
    custom-3751: 'Three Blocks per Row'
    custom-6453: 'Four Blocks per Row'
    custom-6496: 'Four Blocks per Row'
    custom-3872: 'Four Blocks per Row'
    custom-9371: 'Four Blocks per Row'
    custom-9988: 'Different Width Examples'
    custom-4289: '25% Width Block'
    custom-1256: '75% Width Block'
    custom-2720: '25% Width Block'
    custom-5527: '26% Width Block'
    custom-1752: '31% Width Block'
    custom-4132: '43% Width Block'
  messages:
    system-messages-8611: 'System Messages'
  position:
    position-position-4841: 'Header A'
    position-position-5249: 'Above A'
    position-position-8705: 'Feature A'
    position-position-3866: 'Showcase A'
    position-position-2804: 'Sidebar A'
    position-position-8349: 'MainBar A'
    position-position-4370: 'Aside A'
    position-position-9691: 'Expanded A'
    position-position-2600: 'Extension A'
    position-position-9141: 'Bottom A'
  content:
    system-content-7538: 'Page Content'
  newsletter:
    newsletter-3046: Newsletter
  simplemenu:
    simplemenu-6608: 'Simple Menu'
  particlesjs:
    particlesjs-8730: Particles
  copyright:
    copyright-1990: Copyright
  mobile-menu:
    mobile-menu-2642: 'Mobile Menu'
inherit:
  default:
    top: top
    logo-9841: logo-2704
    menu-7574: menu-2872
    social-2794: social-3096
    header: header
    above: above
    feature: feature
    showcase: showcase
    utility: utility
    sidebar: sidebar
    mainbar: mainbar
    aside: aside
    expanded: expanded
    extension: extension
    bottom: bottom
    footer: footer
    copyright: copyright
    offcanvas: offcanvas
    system-messages-8611: system-messages-9828
    position-position-4841: position-position-7051
    position-position-5249: position-position-3264
    position-position-8705: position-position-7980
    position-position-3866: position-position-9435
    position-position-2804: position-position-9414
    position-position-8349: position-position-8547
    system-content-7538: system-content-1120
    position-position-4370: position-position-8807
    position-position-9691: position-position-8124
    position-position-2600: position-position-4800
    position-position-9141: position-position-3343
    logo-9485: logo-8823
    newsletter-3046: newsletter-4035
    social-3786: social-5890
    simplemenu-6608: simplemenu-2324
    particlesjs-8730: particlesjs-4690
    copyright-1990: copyright-6444
    mobile-menu-2642: mobile-menu-2576
